=== Vonage/gosrvlib/examples/service/resources/etc/gosrvlibexample/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "gosrvlibexample config",
  "description": "JSON schema for gosrvlibexample configuration",
  "type": "object",
  "properties": {
    "remoteConfigProvider": {
      "description": "Remote configuration source (if any)",
      "type": "string",
      "default": "",
      "enum": [
        "",
        "consul",
        "etcd",
        "envvar"
      ]
    },
    "remoteConfigEndpoint": {
      "description": "Remote configuration URL (ip:port)",
      "type": "string",
      "default": ""
    },
    "remoteConfigPath": {
      "description": "Remote configuration path in which to search for the configuration file (e.g. '/config/gosrvlibexample')",
      "type": "string",
      "default": ""
    },
    "remoteConfigSecretKeyring": {
      "description": "Path to the openpgp secret keyring used to decrypt the remote configuration data (e.g. '/etc/gosrvlibexample/configkey.gpg'); if empty a non secure connection will be used instead",
      "type": "string",
      "default": ""
    },
    "log": {
      "description": "Logging settings",
      "type": "object",
      "properties": {
        "format": {
          "description": "Defines the default log format",
          "type": "string",
          "default": "JSON",
          "enum": [
            "CONSOLE",
            "JSON"
          ]
        },
        "level": {
          "description": "Defines the default log level",
          "type": "string",
          "default": "DEBUG",
          "enum": [
            "EMERGENCY",
            "ALERT",
            "CRITICAL",
            "ERROR",
            "WARNING",
            "NOTICE",
            "INFO",
            "DEBUG"
          ]
        },
        "network": {
          "description": "(OPTIONAL) Network type used by the Syslog",
          "type": "string",
          "default": "",
          "enum": [
            "",
            "udp",
            "tcp"
          ]
        },
        "address": {
          "description": "(OPTIONAL) Network address of the Syslog daemon (ip:port) or just (:port)",
          "type": "string",
          "default": ""
        }
      },
      "additionalProperties": false,
      "required": [
        "level",
        "network",
        "address"
      ]
    },
    "enabled": {
      "description": "Enable or disable the service",
      "type": "boolean",
      "default": true
    },
    "monitoring": {
      "type": "object",
      "title": "Monitoring HTTP server",
      "description": "Configuration of the monitoring server",
      "examples": [
        {
          "address": ":8072",
          "timeout": 60
        }
      ],
      "required": [
        "address",
        "timeout"
      ],
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string",
          "description": "HTTP address (ip:port) or just (:port)",
          "default": "",
          "examples": [
            ":8072"
          ]
        },
        "timeout": {
          "type": "integer",
          "description": "HTTP request timeout [seconds]",
          "examples": [
            60
          ]
        }
      }
    },
    "public": {
      "type": "object",
      "title": "Public HTTP server",
      "description": "Configuration of the public server",
      "examples": [
        {
          "address": ":8071",
          "timeout": 60
        }
      ],
      "required": [
        "address",
        "timeout"
      ],
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string",
          "description": "HTTP address (ip:port) or just (:port)",
          "default": "",
          "examples": [
            ":8071"
          ]
        },
        "timeout": {
          "type": "integer",
          "description": "HTTP request timeout [seconds]",
          "examples": [
            60
          ]
        }
      }
    },
    "ipify": {
      "type": "object",
      "title": "ipify service client",
      "description": "Configuration of the ipify service client",
      "examples": [
        {
          "address": "https://api.ipify.org",
          "timeout": 5
        }
      ],
      "required": [
        "address",
        "timeout"
      ],
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string",
          "description": "Base URL of the service",
          "default": "",
          "examples": [
            "https://api.ipify.org"
          ]
        },
        "timeout": {
          "type": "integer",
          "description": "HTTP client timeout [seconds]",
          "default": 1,
          "examples": [
            1
          ]
        }
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "log",
    "enabled",
    "monitoring",
    "public",
    "ipify"
  ]
}

=== Vonage/gosrvlib/examples/service/resources/test/etc/gosrvlibexample/config.json
{
  "remoteConfigProvider": "",
  "remoteConfigEndpoint": "",
  "remoteConfigPath": "",
  "remoteConfigSecretKeyring": "",
  "enabled": true,
  "log": {
    "format": "JSON",
    "level": "DEBUG",
    "network": "",
    "address": ""
  },
  "monitoring": {
    "address": ":8072",
    "timeout": 60
  },
  "public": {
    "address": ":8071",
    "timeout": 60
  },
  "ipify": {
    "address": "https://test.ipify.url.invalid",
    "timeout": 1
  }
}
