=== Vonage/gosrvlib/examples/service/resources/etc/srvxmplname/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "samplecli config",
  "description": "JSON schema for samplecli configuration",
  "type": "object",
  "properties": {
    "remoteConfigProvider": {
      "description": "Remote configuration source (if any)",
      "type": "string",
      "default": "",
      "enum": [
        "",
        "consul",
        "etcd",
        "envvar"
      ]
    },
    "remoteConfigEndpoint": {
      "description": "Remote configuration URL (ip:port)",
      "type": "string",
      "default": ""
    },
    "remoteConfigPath": {
      "description": "Remote configuration path in which to search for the configuration file (e.g. '/config/samplecli')",
      "type": "string",
      "default": ""
    },
    "remoteConfigSecretKeyring": {
      "description": "Path to the openpgp secret keyring used to decrypt the remote configuration data (e.g. '/etc/samplecli/configkey.gpg'); if empty a non secure connection will be used instead",
      "type": "string",
      "default": ""
    },
    "enabled": {
      "description": "Enable or disable the database synchronization",
      "type": "boolean",
      "default": true
    },
    "serverAddress": {
      "description": "Internal HTTP address (ip:port) or just (:port)",
      "type": "string",
      "default": ":3499"
    },
    "log": {
      "description": "Logging settings",
      "type": "object",
      "properties": {
        "level": {
          "description": "Defines the default log level",
          "type": "string",
          "default": "DEBUG",
          "enum": [
            "EMERGENCY",
            "ALERT",
            "CRITICAL",
            "ERROR",
            "WARNING",
            "NOTICE",
            "INFO",
            "DEBUG"
          ]
        },
        "network": {
          "description": "(OPTIONAL) Network type used by the Syslog",
          "type": "string",
          "default": "",
          "enum": [
            "",
            "udp",
            "tcp"
          ]
        },
        "address": {
          "description": "(OPTIONAL) Network address of the Syslog daemon (ip:port) or just (:port)",
          "type": "string",
          "default": ""
        }
      },
      "additionalProperties": false,
      "required": [
        "level",
        "network",
        "address"
      ]
    },
    "mysql": {
      "description": "Mysql database settings",
      "type": "object",
      "properties": {
        "sourceDSN": {
          "description": "source database DSN in the format: username:password@protocol(address)/dbname?param=value",
          "type": "string",
          "default": ""
        },
        "targetDSN": {
          "description": "target database DSN in the format: username:password@protocol(address)/dbname?param=value",
          "type": "string",
          "default": ""
        }
      },
      "additionalProperties": false,
      "required": [
        "sourceDSN",
        "targetDSN"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "enabled",
    "serverAddress",
    "log",
    "mysql"
  ]
}

=== Vonage/gosrvlib/examples/service/resources/test/etc/srvxmplname/config.json
{
  "remoteConfigProvider": "",
  "remoteConfigEndpoint": "rp1",
  "remoteConfigPath": "rp2",
  "remoteConfigSecretKeyring": "rp3",
  "log": {
    "level": "DEBUG",
    "network": "",
    "address": ""
  },
  "enabled": false,
  "serverAddress": ":3499",
  "mysql": {
    "sourceDSN": "user:pass@tcp(:3306)/source",
    "targetDSN": "user:pass@tcp(:3307)/target"
  }
}
